### ISSUE TITLE
onReset() method is not getting called

### ISSUE THREAD

**Issue by santoshdm** [ArcBees/GWTP#684]
Hi Team,

In my application I am using gwtp version 0.6 with gwt sdk 2.4.0.

I am facing a unusual issue, that is onReset() method is not getting called for any of the presenters loaded after some time, causing data from old session getting populated, as UI components are not getting refreshed and it is not getting fixed till application is restarted(reloaded). This is occurring only at the higher environment and I am not able to replicate the issue at local or lower environment. As we know onReset() won't get called for addToSlot or addToPopupSlot or the setInSlot with false. But in my case it is normal placemanager request is made for a presenter and which includes 2 child presenters, loaded using setInSlot(,). 

Also I am not getting any exception which could possibly ended the thread from calling onReset().

I am not sure if this issue is been reported and answered, but I was not able to find. Please help me with possible cause for this, which could have triggered this unusual state.

Your help is appreciated.

Regards,
Santosh

**Comment by olafleur** [comment]
Do you still have this problem? If your application is not too big, I would suggest switching to a more recent version of GWTP, step by step, by following the different migration guides located starting here : http://dev.arcbees.com/gwtp/resources/Migrating-from-07-to-10.html

This probably has been fixed in one of the recent versions.

Feel free to ask questions if you need help!
