### ISSUE TITLE
Use of abstract BatchAction is not well documented

### ISSUE THREAD

**Issue by matrousse** [ArcBees/GWTP#693]
BatchAction is an abstract class, it is not clear how to use it (and the corresponding handler).

I have found this old post : https://groups.google.com/forum/#!topic/gwt-platform/SEpDbL2tNvY

I have tried to make a UnsecuredBatchAction but BatchAction constructor is package protected...

**Comment by Chris-V** [comment]
The class is abstract because you need to create your own instance, extend it and then bind the action to the BatchActionHandler on the server side. The empty constructor is package-protected because (as pointed out by the javadoc on it) it is needed for serialization. You need to use the protected overload.

The second post in the thread you posted is still good: https://groups.google.com/d/msg/gwt-platform/SEpDbL2tNvY/CCYLO0d1EwEJ

**Comment by olafleur** [comment]
@matrousse : did you manage to do what you wanted? If yes, you can close that issue.
