### ISSUE TITLE
Gin Future

### ISSUE THREAD

**Issue by spirylics** [ArcBees/GWTP#783]
Hi,
I would like to know what are the prospects about dependency injection with gin ?
Gin has no update since 3 years and has a guice major version delay (4) and dagger-gwt landed.

Thanks,

**Comment by timeu** [comment]
Related: https://github.com/tbroyer/gwt-maven-archetypes/commit/667955ca5243f480a2cc106c324d12c0ed6a783b

I think it makes sense to consider moving GWTP from Guice/GIN to Dagger.

**Comment by olafleur** [comment]
Hi @spirylics !

As @timeu says, it makes sense to move from Gin to Dagger, so that's what we are in the process of doing. If you want to help us with that, @Chris-V is in charge of the transition. It should be completed in the months to come.

**Comment by Chris-V** [comment]
AFAIC, gin is dead. I've seen a fork with a port to Guice 4, but that's about it. If google ever decides to release it we'll u^grade the 1.x branch. Otherwise, I'm not putting any effort in it. Anyways with GWT 3, GWT's code generation is likely to go away in favor of Java's APT. I don't see why gin would be ported when Dagger is already built around annotation processors.

As for GWTP, we will move to Dagger 2. However we first had to port our code generators to annotation processors. The migration to Dagger is not likely to happen overnight and because of breaking changes, it will only be part of GWTP 2. We have many plans for that major release so it'll be ready when it's ready; _no estimates_

( Big bracket here: there's a snapshot of 2.0; use it if you dare. There are a couple known gotchas and annoyances, but it works... I will answer general questions, but I will not perform bug fixes on demand ;) )

In the meantime, we successfully used the latest GWT snapshot with GIN and GWTP. Just make sure your client code is in a different project if you want to use different libraries on your server.

**Comment by spirylics** [comment]
Thanks for your answers. I guess it's a big job to migrate from gin to dagger.
So, if dagger is already in GWTP 2 roadmap, what is the future of Jukito ?
Jukito is useful server side but client side too...

**Comment by Chris-V** [comment]
Jukito only uses Guice behind the scenes to handle DI. But really, if you use JSR-330's annotations (javax.inject.\*, ...) and use Jukito to properly unit test (so no install of production modules, right), everything will tie in smoothly. We did it for projects using Spring, Guice and Dagger without any issues.

**Comment by spirylics** [comment]
Ok, good news, no regret to use GWTP so :)
Thanks for your job.

**Comment by spirylics** [comment]
Hello, it's me :)
I would like to know if somebody had strange errors with junit test with gwtp/jukito. It's a dark story between java8 lambda and gin(guice3)...

http://stackoverflow.com/questions/28244342/why-is-a-lambda-expression-breaking-guice-error-handling-when-i-try-to-start-jet

a workaround ?
some news with dagger ?
